In [1]:
import pandas as pd
import numpy as np

In [2]:
data=[10,20,30,"A",40]
series=pd.Series(data)
print(series)

0    10
1    20
2    30
3     A
4    40
dtype: object


In [3]:
data=[10,20,30,20.5,40,9.81]
series=pd.Series(data)
print(series)

0    10.00
1    20.00
2    30.00
3    20.50
4    40.00
5     9.81
dtype: float64


In [4]:
data=[10,20,30,20,40,9]
series=pd.Series(data)
print(series)

0    10
1    20
2    30
3    20
4    40
5     9
dtype: int64


In [5]:
data=[10,20,30,40,12,80]
i=['a','b','c','d','e','f']
series=pd.Series(data,index=i)
print(series)

a    10
b    20
c    30
d    40
e    12
f    80
dtype: int64


In [6]:
data={'a':10,'b':20,'c':30,'d':5}
series=pd.Series(data)
print(series)

a    10
b    20
c    30
d     5
dtype: int64


In [7]:
data=np.array([10,20,30,40,50,60])
i=['a','b','c','d','e','f']
series=pd.Series(data,index=i)
print(series)

a    10
b    20
c    30
d    40
e    50
f    60
dtype: int32


In [8]:
data=np.array([10,20,30,40,50,60])
i=['a','b','c','d','e','f']
series=pd.Series(data,index=i)
series.replace(40,400)
print(series)

a    10
b    20
c    30
d    40
e    50
f    60
dtype: int32


In [9]:
import pandas as pd
data={'Name':['Alice','Bob','Mary','John'],\
      'Age':[25,30,34,56],\
      'Country':["USA","UK","AUS","INDIA"]}
i=['a','b','c','d']
df=pd.DataFrame(data,index=i)
print(df)

    Name  Age Country
a  Alice   25     USA
b    Bob   30      UK
c   Mary   34     AUS
d   John   56   INDIA


In [10]:
import pandas as pd
data={'Name':['Alice','Bob','Mary','John'],\
      'Age':[25,30,34,56],\
      'Country':["USA","UK","AUS","INDIA"]}
i=['a','b','c','d']
df=pd.DataFrame(data,index=i)
print(df)

    Name  Age Country
a  Alice   25     USA
b    Bob   30      UK
c   Mary   34     AUS
d   John   56   INDIA


In [11]:
import numpy as np
array=np.array([[10,5,20],[14,25,6],[7,18,29]])
print(array)
df=pd.DataFrame(array)
print(df)

[[10  5 20]
 [14 25  6]
 [ 7 18 29]]
    0   1   2
0  10   5  20
1  14  25   6
2   7  18  29


In [12]:
import numpy as np
array=np.array([[10,5,20],[14,25,6],[7,18,29]])
print(array)
df=pd.DataFrame(array,columns=["C1","C2","C3"])
print(df)

[[10  5 20]
 [14 25  6]
 [ 7 18 29]]
   C1  C2  C3
0  10   5  20
1  14  25   6
2   7  18  29


In [13]:
import numpy as np
array=np.array([[100,950],[90,950],[80,850],[70,650],[85,750],[100,950],[100,950],[100,970]])
i=['Sem1','Sem2','Sem3','Sem4','Sem5','Sem6','Sem7','Sem8']
print(array)
df=pd.DataFrame(array,index=i,columns=["attendance","marks"])
print(df)

[[100 950]
 [ 90 950]
 [ 80 850]
 [ 70 650]
 [ 85 750]
 [100 950]
 [100 950]
 [100 970]]
      attendance  marks
Sem1         100    950
Sem2          90    950
Sem3          80    850
Sem4          70    650
Sem5          85    750
Sem6         100    950
Sem7         100    950
Sem8         100    970


In [14]:
iris_df=pd.read_csv("iris.csv")
print(iris_df)

     sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]


In [15]:
iris_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal.length  150 non-null    float64
 1   sepal.width   150 non-null    float64
 2   petal.length  150 non-null    float64
 3   petal.width   150 non-null    float64
 4   variety       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [16]:
iris_df.head(5)

sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [17]:
iris_df.tail(5)

sepal.length  sepal.width  petal.length  petal.width    variety
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

In [18]:
iris_df.head(150)

sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]

In [19]:
iris_df.describe()

sepal.length  sepal.width  petal.length  petal.width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [20]:
print(iris_df.shape)
print(iris_df.ndim)
print(iris_df.size)

(150, 5)
2
750


In [21]:
iris_df.iloc[10:21,:]

sepal.length  sepal.width  petal.length  petal.width variety
10           5.4          3.7           1.5          0.2  Setosa
11           4.8          3.4           1.6          0.2  Setosa
12           4.8          3.0           1.4          0.1  Setosa
13           4.3          3.0           1.1          0.1  Setosa
14           5.8          4.0           1.2          0.2  Setosa
15           5.7          4.4           1.5          0.4  Setosa
16           5.4          3.9           1.3          0.4  Setosa
17           5.1          3.5           1.4          0.3  Setosa
18           5.7          3.8           1.7          0.3  Setosa
19           5.1          3.8           1.5          0.3  Setosa
20           5.4          3.4           1.7          0.2  Setosa

In [22]:
iris_df.iloc[10:21,[0,3]]

sepal.length  petal.width
10           5.4          0.2
11           4.8          0.2
12           4.8          0.1
13           4.3          0.1
14           5.8          0.2
15           5.7          0.4
16           5.4          0.4
17           5.1          0.3
18           5.7          0.3
19           5.1          0.3
20           5.4          0.2

In [23]:
iris_df.loc[10:21,"sepal.length":"petal.length"]

sepal.length  sepal.width  petal.length
10           5.4          3.7           1.5
11           4.8          3.4           1.6
12           4.8          3.0           1.4
13           4.3          3.0           1.1
14           5.8          4.0           1.2
15           5.7          4.4           1.5
16           5.4          3.9           1.3
17           5.1          3.5           1.4
18           5.7          3.8           1.7
19           5.1          3.8           1.5
20           5.4          3.4           1.7
21           5.1          3.7           1.5

In [24]:
iris_df.loc[10:21:5,"sepal.length":"petal.length"]

sepal.length  sepal.width  petal.length
10           5.4          3.7           1.5
15           5.7          4.4           1.5
20           5.4          3.4           1.7

In [25]:
data={"weight":[66,75,84,96,48,71],\
     "Height":[156,165,186,165,174,167]}
bmi=pd.DataFrame(data)
print(bmi)

   weight  Height
0      66     156
1      75     165
2      84     186
3      96     165
4      48     174
5      71     167


In [26]:
bmi["BMI"]=bmi["weight"]/(bmi["Height"]/100)**2
bmi

weight  Height        BMI
0      66     156  27.120316
1      75     165  27.548209
2      84     186  24.280264
3      96     165  35.261708
4      48     174  15.854142
5      71     167  25.458066

In [27]:
bmi.loc[3]=[78,np.nan,np.nan]
bmi

weight  Height        BMI
0      66   156.0  27.120316
1      75   165.0  27.548209
2      84   186.0  24.280264
3      78     NaN        NaN
4      48   174.0  15.854142
5      71   167.0  25.458066

In [28]:
bmi.loc[5]=[np.nan,65,np.nan]
bmi

weight  Height        BMI
0    66.0   156.0  27.120316
1    75.0   165.0  27.548209
2    84.0   186.0  24.280264
3    78.0     NaN        NaN
4    48.0   174.0  15.854142
5     NaN    65.0        NaN

In [60]:
bmi.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   weight  5 non-null      float64
 1   Height  5 non-null      float64
 2   BMI     4 non-null      float64
dtypes: float64(3)
memory usage: 276.0 bytes


In [62]:
bmi.isnull().sum()

weight    1
Height    1
BMI       2
dtype: int64

In [64]:
bmi["weight"]=bmi["weight"].fillna(65)
bmi

weight  Height        BMI
0    66.0   156.0  27.120316
1    75.0   165.0  27.548209
2    84.0   186.0  24.280264
3    78.0     NaN        NaN
4    48.0   174.0  15.854142
5    65.0    65.0        NaN

In [66]:
bmi["Height"]=bmi["Height"].fillna(165)
bmi

weight  Height        BMI
0    66.0   156.0  27.120316
1    75.0   165.0  27.548209
2    84.0   186.0  24.280264
3    78.0   165.0        NaN
4    48.0   174.0  15.854142
5    65.0    65.0        NaN

In [68]:
bmi["BMI_NEW"]=bmi["weight"]/(bmi["Height"]/100)**2
bmi

weight  Height        BMI     BMI_NEW
0    66.0   156.0  27.120316   27.120316
1    75.0   165.0  27.548209   27.548209
2    84.0   186.0  24.280264   24.280264
3    78.0   165.0        NaN   28.650138
4    48.0   174.0  15.854142   15.854142
5    65.0    65.0        NaN  153.846154

In [70]:
import matplotlib.pyplot as plt
plt.hist(iris_df["sepeal.legth"],color="blue")

KeyError: 'sepeal.legth'